spring:
  application.name: eureka-server
security.basic.enabled: false
netflix:
  appinfo.name: ${spring.application.name}
server.port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
